### ISSUE TITLE
Much larger output file sizes than input file sizes

### ISSUE THREAD

**Issue by jford8820** [salsify/arc-furnace#16]
One of our projects has a `ProductPipeline` that is a relatively simple implementation of the library. Here's a snippet:

```
require_relative 'constants'
require 'arc-furnace/pipeline'
require 'arc-furnace/excel_source'
require 'arc-furnace/all_fields_csv_sink'

class ProductsPipeline < ArcFurnace::Pipeline

  include Constants

  # create products source

  source :products_source,
         type: ArcFurnace::ExcelSource,
         params: {
             filename: :product_filename,
             encoding: 'ISO-8859-1'
         }

  transform :products_transform, params: { source: :products_source } do |hash|
    result = hash.deep_dup
    result[SALSIFY_ID] = result.delete(BLAH_ID)
    result
  end

  filter :filtered_products, params: { source: :products_transform, observed_products: :observed_products } do |row, params|
    params.fetch(:observed_products).add(row[BLAH_ID])
  end

  sink type: ArcFurnace::AllFieldsCSVSink,
       source: :filtered_products,
       params: { filename: "#{Dir.pwd}/products_import.csv" }

end
```

The source file is a 14 MB XLSX file, but the output file is a 71 MB CSV file. The output file is five times larger and XLSX files tend to be larger than CSV files relative to the information contained. I tried removing the filter and the file size was the same, and I spot checked the file and they look identical. I feel like something is going wrong with the `AllFieldsCSVSink`.

Queue @dspangen

**Comment by rlburkes** [comment]
What is the cardinality of values in the input file? An XLSX using shared strings can offer significant savings in terms of space over an uncompressed CSV if there is a large number of duplicates in the data.

**Comment by jford8820** [comment]
There are a ton of duplicates @rlburkes. I had no idea that's how that worked

**Comment by dspangen** [comment]
Have you opened the file and re-saved it? This will force the use of shared strings and could compress it quite a bit...

**Comment by jford8820** [comment]
Yes I did try that @dspangen, @brea9482 suggested it first

**Comment by dspangen** [comment]
Appears to be a non-issue based on @rlburkes observation and other analysis.
